### ISSUE TITLE
Options don't show up

### ISSUE THREAD

**Issue by Akropos** [shteeve3d/blender-wiggle-2#13]
I have installed and enable the add-on on Blender 3.5. Even though it's enabled, the option to enable wiggle bones doesn't show up in the scene, armature or bone menu. I don't know if this is or isn't supposed to work with 3.5.

**Comment by shteeve3d** [comment]
note that the controls for wiggle 2 have been unified as a tab in the 'N' panel in the 3d viewport, this way you can tweak settings with the viewport fullscreen, and don't need to swap between bone/armature/scene property views.

let me know if that addresses your issue! :)

**Comment by Akropos** [comment]
Yes, that seems to be the problem, now that I've found the menu it seems to be working fine. Thanks for your help!
