### ISSUE TITLE
Baked wiggle behaves differently than in real time.

### ISSUE THREAD

**Issue by UrbanTjazPirnar** [shteeve3d/blender-wiggle-2#14]
Hi, I absolutely love this addon, especially the pre roll and collisions. It really makes life easier. The only thing that I noticed is that when I Bake Wiggle, the bones don't behave as they do in real time simulation. I've tried different with different quality settings and so far the only thing that seemed to somewhat fix the problem was to change the frame rate in the output panel before Baking Wiggle. (It seems that if I use 15fps in real time and 30 fps in baked it looks somewhat similar. but if I use 15 or 30 on both baked and real time the bones move a lot less in baked version.) Perhaps there are some simulation time settings that I have missed but so far i haven't found the solution yet. 
I'm using Blender 3.2.2 and Wiggle 2.2.

The woman in the screenshot in moving left.

Tx again for the addon.

![Baked Issue](https://github.com/shteeve3d/blender-wiggle-2/assets/79314193/c1a7e7af-321b-4363-91de-3af1c0561bfa)

**Comment by UrbanTjazPirnar** [comment]
Update. I moved my rig to a fresh file and now it seems to be working perfectly. Perhaps it was something with the old wiggle bones addon that stayed enabled even after disabling the addon and messed with the wiggle physics.
Anyway it works now.

**Comment by shteeve3d** [comment]
Glad it’s working better!

Another thing to consider is whether your viewport playback settings are set to play every frame, or one of the frame dropping options. If it’s dropping frames it might change the quality of wiggle motion, whereas the bake will always calculate every frame. 

Is it possible the fresh file just had less stuff in it, allowing the playback without dropped frames?

**Comment by UrbanTjazPirnar** [comment]
I just copypasted everything from the original file into the new one. I didn't use frame dropping. Maybe the original file was created in an earlier version of blender but I'm not sure. 
Here are both of the files if you wish to debug. (I deleted everything except a simple chain of bones for testing) https://drive.google.com/file/d/1xX2ZCwsYdc1Kc-QNEs97Eq81qXXfX9si/view?usp=sharing
If you try to bake wiggle you will see.

**Comment by shteeve3d** [comment]
thanks for the test file! i can confirm i'm seeing weird bake issues in the original file. i'll look into what could be causing it!

**Comment by shteeve3d** [comment]
as a small update, i isolated the issue to one that i believe plagued my previous version as well - a file with multiple view layers seems to trigger the evaluation of the wiggle effect in unpredictable ways for things like baking. removing the second view layer from the problematic file immediately made baking work as expected.

i'll keep investigating to see if i can find better ways to get bakes to only consider the active view layer, but so far my attempts haven't helped and only added instability. in the mean time i figured it might be helpful to at least share what was triggering the issue!
