### ISSUE TITLE
Issue with damped track affecting a chain

### ISSUE THREAD

**Issue by KroneDev22** [shteeve3d/blender-wiggle-2#16]
I have a chain of wiggle bones, about 9 long, and for some reason when I add the damped track to the end, it seems to only affect the tip + the previous bone in the chain by a small amount, or the entire chain contorts in a rather weird way, while the end bone with the constraint on it stretches in a way to try to reach the target. 

I've tried altering the gravity, weight, stiffness, dampening, as well as using an empty as the target or a bone in the same armature. 
Having the end bone weigh more than the rest of the chain seemed to affect the chain in a positive way in regards to the damped tracking (still not working as intended), but would result in undesired movement when the influence was turned off (not in a bug way, just undesired).

The settings from Mass - Gravity, are 1.0 / 22.0 / 0 / 15 / 0.7
The end bone, has a stiffness of 222, and the bone before it, has 111.

**Comment by shteeve3d** [comment]
try upping the “quality” property in the global wiggle settings to the number of bones in your bone chain to see if that helps!

**Comment by KroneDev22** [comment]
Quality 8
![image](https://github.com/shteeve3d/blender-wiggle-2/assets/120227099/949e6e3e-86eb-4e6b-bf6c-0028c86774e7)
Quality 2
![image](https://github.com/shteeve3d/blender-wiggle-2/assets/120227099/4b40acb0-afea-4b1b-8ea3-e209565eab44)
Attempted to add images (turns out they worked). Appreciate the response. 

It helped somewhat, but still has stretching. I've noticed that if the damped track target is set to a bone in the same armature, it gets quite wonky results. But using an empty seems to have largely better results.

I also just tried fiddling with the settings again, some things kind of helped get the damped track working, but it never worked fully. And changing the settings would result in undesired non-damped track wiggle.

I may try either an IK set up, or a spline IK and see what results I can get instead.
Cheers.

**Comment by shteeve3d** [comment]
Oh! The bone target for damped track is actually something that had been flagged to me before and should actually be fixed in the 2.2.1 branch that I just haven’t officially promoted to being a release.

As for the stretching, that still persists a bit even as you raise the quality, I’ll take a look at that, as I can replicate that on my end too.

**Comment by shteeve3d** [comment]
i just posted the 2.2.1 release, that hopefully should improve some of your issues, including the excessively stretchy pinned bone! see details here:
https://github.com/shteeve3d/blender-wiggle-2/releases/tag/v2.2.1
