### ISSUE TITLE
Restoring bone physics settings after baking

### ISSUE THREAD

**Issue by jamesWalker55** [shteeve3d/blender-wiggle-2#28]
After baking bone physics to an action, is it possible to restore the Wiggle settings used for a bone?

On Blender 3.6, I've baked physics for some bones then re-enabled Wiggle on the scene. The bones no longer have the settings I've set before the bake.

**Comment by shteeve3d** [comment]
are you able to share an example file?

i'm not able to replicate this issue. when i bake using the 'bake wiggle' operator, it "freezes" the armature from further live calculations. if you delete the baked keyframes, you can then hit the snowflake icon to "unfreeze" the armature and all the existing wiggle settings are preserved.
<img width="255" alt="Screenshot 2023-07-12 at 8 46 10 PM" src="https://github.com/shteeve3d/blender-wiggle-2/assets/126594110/4632d4bb-3193-44ce-8c2a-09c004d1a6d6">

alternatively, baking using blender's 'bake action' operator, and then disabling the armature wiggle has the same result. you can delete the baked keyframes and re-enable the armature and all the individual bone settings should be preserved.

**Comment by jamesWalker55** [comment]
Apologies, it seems I can't seem to reproduce it either, this might have been user error. I'm using the Rigify addon which generates new armatures, so that might have overwrote data from the old armature.

I'll close the issue for now, if I'm able to reproduce the issue in the future I'll reopen this issue.
