### ISSUE TITLE
Weird bouncing effect after turning on gravity

### ISSUE THREAD

**Issue by TheRealA77** [shteeve3d/blender-wiggle-2#32]
Hello, i have just downloaded your addon and it looks very complete and well designed. I am unfortunately facing a problem with the back spines of my model. The video is pretty self explanatory. How do i stop that weird bouncing effect i get when turning on gravity?

https://github.com/shteeve3d/blender-wiggle-2/assets/72188131/3d29a52c-a056-4192-9d50-03b0fcc998ee

**Comment by shteeve3d** [comment]
that definitely looks weird. i'd probably need to know more about the rig to really isolate the problem. i was getting some glitches when trying to calculate wiggle on non uniform scaled bone heirarchies, but its tough to tell from a screen recording alone. is there any simplified blend file you can share that demonstrates the problem?

**Comment by TheRealA77** [comment]
if there's any way i can send it to you privately, i can hand you the whole rig

**Comment by TheRealA77** [comment]
you are right, kenw. It doens't do it when the "play every frame" option is enabled, but it does it otherwise. I can kinda work with this but a fix to it, if possible, would be much appreciated

https://github.com/shteeve3d/blender-wiggle-2/assets/72188131/9032f7c1-ae2d-4b78-8c09-cda51a47a68c
