### ISSUE TITLE
Code>Download ZIP did not install

### ISSUE THREAD

**Issue by DaddehGhost** [shteeve3d/blender-wiggle-2#5]
First off: Forgive me, I'm a GH newbie..

I couldn't find the ZIP so I assumed I had to use the Code>Download ZIP to get the addon.

I tried importing into Blender and it seemed successful - only it doesn't show in the Addons list.

Did I do everything right and it just didn't want to load?

I'm using 3.4 currently.

**Comment by madcoffee** [comment]
extract the zip and install the .py

**Comment by DaddehGhost** [comment]
> 

I installed the .py but the add-in did not appear.

**Comment by DaddehGhost** [comment]
> extract the zip and install the .py

Took a while but it seems to have worked - thanks!
