### ISSUE TITLE
Bone Head Scaling broken

### ISSUE THREAD

**Issue by RazorWolvendom** [shteeve3d/blender-wiggle-2#6]
every bone where i want the bone to have the physics active on the Head of the bone, will scale and stretch to a certain size when "inherit Scale" is set to Full even tho the scale is still on its default scale of 1.0.

it can be bypassed by changing the inherit scale method to "None"

<img width="1010" alt="ScreenShot_20230411205940" src="https://user-images.githubusercontent.com/44827474/231263838-8eec54ed-3d90-414e-81d5-bdfc49186571.png">

**Comment by shteeve3d** [comment]
i was actually going to look into this one a little bit to see if its a known limitation or a bug i overlooked. how did you manage to resolve it @RazorWolvendom ?

**Comment by RazorWolvendom** [comment]
> i was actually going to look into this one a little bit to see if its a known limitation or a bug i overlooked. how did you manage to resolve it @RazorWolvendom ?

it was due to the bone properties that Controls inhertitations so aslong its on "Full" it will stretch insanely like that, but if you Change it to "None" it behaves as it should.
