### ISSUE TITLE
Damped track and Track to leading to contorting when influence is 0

### ISSUE THREAD

**Issue by uwuziel** [shteeve3d/blender-wiggle-2#7]
When a wiggle bone's Track To constraint is set to 0, the bone will still track along the non-up axis to the track object's starting position. It gets worse with bones, if you select a bone on the same armature as a tracking object, the wiggle bone scaling and rotation will be out of whack.

**Comment by shteeve3d** [comment]
good catch on bone pinning targets. fixing that one for sure. i'm not sure if i fully understand the other issue. do you mean the constraint influence is set to 0? the wiggle bone seems to behave as expected for me when the constraint influence is 0. 

also, i currently am only supporting the 'damped track' constraint for the pinning effect. i might try adding the other tracking constraints.

**Comment by shteeve3d** [comment]
I hopefully was able to address the issues you were having with setting bone targets for tracking constraints, as well as supporting more types of tracking constraints. see details in the release page:
https://github.com/shteeve3d/blender-wiggle-2/releases/tag/v2.2.1
